name: Run Tox

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:${{ matrix.python-version }}-alpine
      volumes:
        - /github/home/.cache/pip:/github/home/.cache/pip

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: install system dependencies
        run: |
          apk add --no-cache libffi-dev build-base git

      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: install python dependencies
        run: |
          pip install -U pip
          pip install tox

      - name: run tox
        run: tox

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-xml-coverage-path: ./coverage.xml
          junitxml-path: ./pytest.xml
          remove-link-from-badge: true
